export const SIGNIN = 'SIGNIN'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_ERROR = 'SIGNIN_ERROR'
export const SIGNUP = 'SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNOUT = 'SIGNOUT'
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
/*
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS'
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'
export const SIGNIN_WITH_GITHUB = 'SIGNIN_WITH_GITHUB'
export const ON_AUTHSTATE_CHANGED = 'ON_AUTHSTATE_CHANGED'
export const SET_AUTH_PERSISTENCE = 'SET_AUTH_PERSISTENCE'
export const ON_AUTHSTATE_SUCCESS = 'ON_AUTHSTATE_SUCCESS'
export const ON_AUTHSTATE_FAIL = 'ON_AUTHSTATE_FAIL'
*/
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const GET_USER = 'GET_USER'

export const LOADING = 'LOADING'

export const SEARCH_ARTICLE = `SEARCH_ARTICLE`

export const FETCH_ARTICLE = `FETCH_ARTICLE`
export const FETCH_ARTICLE_SUCCESS = `FETCH_ARTICLE_SUCCESS`
export const FETCH_ARTICLE_FAILURE = `FETCH_ARTICLE_FAILURE`

export const FETCH_ARTICLES = `FETCH_ARTICLES`
export const FETCH_ARTICLES_SUCCESS = `FETCH_ARTICLES_SUCCESS`
export const FETCH_ARTICLES_FAILURE = `FETCH_ARTICLES_FAILURE`

export const ADD_ARTICLE = `ADD_ARTICLE`
export const ADD_ARTICLE_SUCCESS = `ADD_ARTICLE_SUCCESS`
export const ADD_ARTICLE_FAILURE = `ADD_ARTICLE_FAILURE`

export const DELETE_ARTICLE = `DELETE_ARTICLE`
export const DELETE_ARTICLE_SUCCESS = `DELETE_ARTICLE_SUCCESS`
export const DELETE_ARTICLE_FAILURE = `DELETE_ARTICLE_FAILURE`

export const UPDATE_ARTICLE = `UPDATE_ARTICLE`
export const UPDATE_ARTICLE_SUCCESS = `UPDATE_ARTICLE_SUCCESS`
export const UPDATE_ARTICLE_FAILURE = `UPDATE_ARTICLE_FAILURE`
